[package]
org = "sachinira"
name = "template_update_gsheetrows_to_sfdc_sobjects"
version = "0.1.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "googleapis_sheets"
version = "0.99.7"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.5"
