[[dependency]]
org = "ballerina"
name = "log"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerina"
name = "http"
version = "1.1.0-alpha7"

[[dependency]]
org = "ballerinax"
name = "googleapis_sheet"
version = "0.99.7"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.7"

